global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus_django_uwsgi'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']