global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django.rules.yml"

scrape_configs:
  - job_name: 'prometheus-django-metrics'
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'graphana'
    static_configs:
      - targets: ['localhost:3000']
